name: HomeStar
main: com.winterhaven_mc.homestar.PluginMain
author: ${project.author}
version: ${project.version}
api-version: 1.17
softdepend: [Multiverse-Core]

commands:
  homestar:
    description: Use /homestar help [subcommand] to view subcommand help.
    usage: /homestar [command]

permissions:
  homestar.use:
    description: Allows the use of a HomeStar.
    default: true

  homestar.help:
    description: Allows display of help for HomeStar subcommands.
    default: true

  homestar.status:
    description: Allows display of configuration settings.
    default: op

  homestar.reload:
    description: Allows reloading the configuration file.
    default: op

  homestar.give:
    description: Allows giving HomeStar items to players.
    default: op

  homestar.destroy:
    description: Allows destroying HomeStar items in hand.
    default: op

  homestar.admin:
    description: Allows all admin commands
    default: op
    children:
      homestar.status: true
      homestar.reload: true
      homestar.give: true
      homestar.destroy: true
